# Custom Language File for Launcher Customizer

[ejs.app]
title = "Reboot Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Si le launcher marche c fou"
welcomeDescription = "mdr si il amrche ratrappe le"
welcomeDescCTA = "Bip boup je suis un robot lol"
